export const items = [
  "🦖 Dinosaur",
  "🐉 Dragon",
  "🦄 Unicorn",
  "🔥 Phoenix",
  "🦅 Griffin",
  "🧜‍♀️ Mermaid",
  "🐎 Centaur",
  "🐍 Basilisk",
  "🐉 Hydra",
  "🦁 Sphinx",
  "🐴 Pegasus",
  "🐐 Chimera",
  "🐂 Minotaur",
  "🧚 Fairy",
  "🪨 Golem",
  "❄️ Yeti",
  "🐙 Kraken",
  "🦇 Bat",
  "🦒 Giraffe",
  "🐉 Wyvern",
  "🐲 Salamander",
  "🦓 Zebra",
  "🐻 Bear",
  "🐾 Werewolf",
  "🦚 Peacock",
  "🐅 Tiger",
  "🐊 Crocodile",
  "🦙 Llama",
  "🐉 Naga",
  "🦕 Brontosaurus",
  "🦈 Shark",
  "🐉 Cerberus",
  "🦚 Harpy",
  "🌊 Leviathan",
  "🐉 Manticore",
  "🌪️ Djinn",
  "🌌 Banshee",
  "🦄 Kirin",
  "🌊 Selkie",
  "🎭 Kitsune",
  "👻 Poltergeist",
  "🔮 Oracle",
  "🐯 Sabertooth Tiger",
  "🦕 Plesiosaurus",
  "🌌 Thunderbird",
  "🔱 Triton",
  "🎆 Chupacabra",
  "🌪️ Wendigo",
  "👺 Oni",
  "🎩 Jackalope",
  "🌲 Bigfoot",
  "🌊 Kraken",
  "💧 Nymph",
  "🎭 Harlequin",
  "🎨 Gorgon",
  "🐘 Elephant",
  "🦏 Rhinoceros",
  "🐅 Lion",
  "🐼 Panda",
  "🦓 Zebra",
  "🦒 Okapi",
  "🐊 Alligator",
  "🐧 Penguin",
  "🦈 Mako Shark",
  "🦖 Velociraptor",
  "🐒 Capuchin Monkey",
  "🚀 Quokka",
  "🎣 Narwhal",
  "🎸 Anglerfish",
  "🍃 Sloth",
  "🌴 Tapir",
  "🍂 Aardvark",
  "🍃 Manatee",
  "🌊 Dugong",
  "👹 Troll",
  "🌌 Yeti",
  "👺 Goblin",
  "🔮 Fairy Godmother",
  "👻 Specter",
  "⚔️ Valkyrie",
  "⚡ Cyclops",
  "🔱 Leviathan",
  "🪓 Dwarf",
  "🪄 Sorcerer",
  "🦂 Scorpion",
  "🦦 Otter",
  "🌋 Salamandra",
  "🌕 Moon Rabbit",
  "💫 Impunity",
  "🌲 Dryad",
  "🎐 Spirit Fox",
  "🪶 Roc",
  "🪽 Seraphim",
  "🌠 Star Whale",
  "💎 Crystal Serpent",
  "🔥 Ifrit",
  "🌙 Moon Elf",
  "🧿 Djinni",
  "🪻 Moss Sprite",
  "🌈 Rain Dragon",
  "❄️ Frost Giant",
  "🌋 Magma Elemental",
  "🪸 Sea Serpent",
  "🧙‍♀️ Witch",
];
